name: Build and Release Fabric Mod

on:
  push:
    branches:
      - main
  create:
    tags:
      - '*'

jobs:
  build:
    name: Build Fabric Mod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build the mod
        run: ./gradlew build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: FabricMod-Build
          path: build/libs/*.jar

  create-tag:
    name: Create GitHub Tag
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create and push tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
          git tag $TAG_NAME
          git push origin $TAG_NAME

  release:
    name: Create GitHub Release
    needs: create-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: FabricMod-Build
          path: build/libs/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Automated release for ${{ github.ref_name }}"
          draft: false
          prerelease: false
